<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <RootNamespace>EplanEdzManager.EplanBridge.Client</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EplanEdzManager.EplanBridge.Protocol\EplanEdzManager.EplanBridge.Protocol.csproj" />
  </ItemGroup>
</Project>
